### ISSUE TITLE
Channel 1 scaling factor is used to scale all channels

### ISSUE THREAD

**Issue by aaronshifman** [swharden/pyABF#3] opened 2018-03-31 20:00 UTC
Hi Scott,

We have an ABF file with 2 channels. Channel 0 is membrane potential which is recovered correctly. Channel 1 is an analog output from a temperature recorder.

The temperature is scaled as 2.3 + 10*T and when the ABF file is read into the software that generated it, it displays and formats correctly. However when it's read into python /w pyabf the temperature is not transformed and the units appear to be set as mV

I've included the ABF file in question along with an example use case 

[example.zip](https://github.com/swharden/pyABF/files/1865850/example.zip)

``` python
import pyabf
abf = pyabf.ABF("example.abf")
abf.setSweep(0, channel=0)
Vm = abf.dataY
t = abf.dataX
abf.setSweep(0, channel=1)
Temp = abf.dataY
#Temp = 2.3 + 10* abf.dataY
```

It's obviously  not a critical issue - but it would be a nice feature (or if I'm doing something wrong, if you could let me know that would be great).

Cheers,
Aaron

**Comment by swharden** [comment] 2018-04-16 01:04
Hi Aaron, thanks for sending this in! 

I reviewed it in detail and I figured out what the problem is (and how to fix it). Unfortunately it's a bit complex, so I'm going to leave this ticket open until I have time to fix it properly. I'm glad your hack works in the mean time!

- I added the ABF you submitted (where channel 2 is Celsius data) to [data/](https://github.com/swharden/pyABF/tree/master/data/) and it now has a [header notes file](https://github.com/swharden/pyABF/blob/master/data/headers/180415_aaron_temp.md) so we can practice working with it.
- The problem is that when any sweep is read with `setSweep()` its contents are scaled using the scaling factor from channel 1. This causes problems when channel 2 is scaled differently than channel 1.

Apparantly I knew this was a problem when I first wrote the software, but never fixed it:
https://github.com/swharden/pyABF/blob/master/src/pyabf/header.py#L210-L225

The scaling occurs in the header.py file, when really it should occur inside setSweep() in abf.py
https://github.com/swharden/pyABF/blob/master/src/pyabf/header.py#L265-L279

**Comment by aaronshifman** [comment] 2018-04-17 02:12
Hi Scott,

Thanks for getting back to me - glad to know I wasn't just missing something super obvious. I did some (albeit, brief) looking with what you sent, and it seems like an interesting problem to say the least, let me know if you want a hand with the fix.

Cheers,
Aaron 

Also as an aside if numpy isn't available, header.py is going to have a problem. [https://github.com/swharden/pyABF/blob/master/src/pyabf/header.py#L273](https://github.com/swharden/pyABF/blob/master/src/pyabf/header.py#L273), you have a global boolean `np` at the top

**Comment by swharden** [comment] 2018-04-17 13:17
Regarding the numpy requirement in the ABF header, I opened a new ticket for this issue:
https://github.com/swharden/pyABF/issues/4

**Comment by swharden** [comment] 2018-06-23 00:00
This issue has been corrected in v2 (which was just merged to master).

I haven't updated pypi (so you can't `pip install --upgrade pyabf` quite yet), but if you're inspired to download the package from this GitHub page it should work for you.

Most core functionality is the same, and the [getting started guide](https://github.com/swharden/pyABF/tree/master/docs/getting-started) is the best place to learn how to use pyABF v2.

**Closed by swharden** 2018-06-23 00:00 UTC
