### ISSUE TITLE
error: unpack requires a buffer of 1 bytes (end of file reached)

### ISSUE THREAD

**Issue by JPacheco5** [swharden/pyABF#131] opened 2023-03-23 01:34 UTC
I have a piece of code on python to open an .abf file. The script worked well except for some files that I did take too much attention. However, after several runs, the code stopped working with all my files. Including those that previously worked. The module shows me the following error:
```
 File ~/opt/anaconda3/lib/python3.9/site-packages/pyabf/abfReader.py:41 in readByte
    values = struct.unpack("B", bytes)

error: unpack requires a buffer of 1 bytes
```
My code is simple:

```
abf = pyabf.ABF("/Users/Jep160/Desktop/S0/23316000.abf")

plt.subplot(211)
abf.setSweep(sweepNumber=0, channel=0)
plt.plot(abf.sweepX, abf.sweepY,'green', label="Channel 1")
```

I don't understand how to solve the problem. Thanks in advanced

**Comment by swharden** [comment] 2023-03-31 03:16
Hi @JPacheco5, thanks for this question! Can you share the entire exception message so we can assess what function is calling for this unpacking?

Alternatively/additionally can you share the ABF you are having trouble opening?

Can you confirm the ABF can successfully be opened by ClampFit or another "official" ABF reading program? It's possible this error message is the result from a damaged ABF file. Thanks!

I'll close this issue now since I can't reproduce it, but if you provide additional information we can open it back up again 👍

**Comment by TheSuperbohl** [comment] 2023-08-16 03:47
Hello, I  have just stumbled upon this same issue myself. I am new to using this but I have a file to batch-read a  Data Directory with only ABFs in it and then put every figure into a data dump. It works flawlessly for about 50-60 files every time without issues. I can then remove the files that were graphed from the Data Directory at the point of error and keep going with the next ABF in sequence. All of these ABFs work as I have gone through this data previously. Thank you for any help you can give. Attached is the error array I receive from Spyder, and it is identical to the one I get if I run from the terminal.
<img width="831" alt="Screenshot 2023-08-15 at 11 39 13 PM" src="https://github.com/swharden/pyABF/assets/142111284/a538a93d-8221-4b10-a204-db14244ce5f2">

**Comment by swharden** [comment] 2023-08-22 01:55
Hi @TheSuperbohl, thanks for extending @JPacheco5's initial issue!

For reference, this is the function that fails:

https://github.com/swharden/pyABF/blob/06247e01ca3c19f5419c3b9b2207ee544e30dbc5/src/pyabf/abfReader.py#L39-L42

Based on the line of code that failed, I think the error is that you are both hitting an ABF file which is incomplete, corrupted, or was deleted or moved after the python program started running. I'll leave this issue open to track adding a more descriptive error message in this spot so a failure produces a more helpful error message.

If anyone hits an ABF file which repeatedly generates this error, first confirm it's not corrupted (e.g., try to look at it in ClampFit), and if pyabf still has problems with it you can upload it here (drag/drop it into the comments window) and I can take a closer look 👍

**Comment by TheSuperbohl** [comment] 2023-08-24 13:39
Hi Scott,
Thank you for reaching back out. Will any incomplete file be considered one that was supposed to be say 8 sweeps but I canceled it after 4 full sweeps? Or is it more likely it's incomplete if I have cut the abf file off in the middle of the defined sweep no matter the actual sweep number. Currently have been testing with a data folder of unsorted raw data that can include both of those situations.

**Comment by swharden** [comment] 2023-10-13 15:36
> Will any incomplete file be considered one that was supposed to be say 8 sweeps but I canceled it after 4 full sweeps? 

No, when you click the "stop" button in ClampEx it writes a little bit of data to the end of the file (things like tag comments), even if you stop after 4 sweeps but there were 8 in the protocol.

It writes to disk every few seconds, but if power is lost (for example) then that little header at the end never gets written, and _that_ is an incomplete file that will throw this error

Hope it helps!

**Closed by swharden** 2023-10-13 15:36 UTC
